trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- powershell: eng\common\build.ps1
    -configuration Debug
    -prepareMachine
    -ci
    -restore
    -test
    -projects $(Build.SourcesDirectory)\src\BuildResultAnalysisTest\BuildResultAnalysisTest.csproj
    /bl:$(Build.SourcesDirectory)\artifacts\log\Debug\Helix.binlog
    /p:RestoreUsingNuGetTargets=false
  displayName: Run Helix Tests
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    HelixAccessToken: ''