trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    jobs:
      - job: Validate_Ali_Test
        displayName: Validate Test
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: $(Build.SourcesDirectory)\eng
              ArtifactName: BuildPublishConfig
            displayName: Publish validation scripts
          - publish: $(Build.SourcesDirectory)\eng
            artifact: BuildConfiguration
            displayName: Publish Build Config
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '**\BuildResultAnalysisTest.csproj'
          - task: VSTest@2
            inputs:
              testSelector: 'testAssemblies'
              testAssemblyVer2: |
                **\BuildResultAnalysisTest.dll
                !**\obj\**
              searchFolder: '$(System.DefaultWorkingDirectory)'
      - job: Validate_Ali_Test_Succeded
        displayName: Validate Test
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: $(Build.SourcesDirectory)\eng
              ArtifactName: BuildPublishConfig
            displayName: Publish validation scripts
          - publish: $(Build.SourcesDirectory)\eng
            artifact: BuildConfiguration
            displayName: Publish Build Config
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '**\SecondaryTests.csproj'
          - task: VSTest@2
            inputs:
              testSelector: 'testAssemblies'
              testAssemblyVer2: |
                **\SecondaryTests.dll
                !**\obj\**
              searchFolder: '$(System.DefaultWorkingDirectory)'
