trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    jobs:
      - job: Validate_Ali_Test
        displayName: Validate Test
        steps:
          - publish: $(Build.SourcesDirectory)\eng
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '**\*.csproj'
          - task: VSTest@2
            inputs:
              testSelector: 'testAssemblies'
              testAssemblyVer2: |
                **\BuildResultAnalysisTest.dll
                !**\obj\**
              searchFolder: '$(System.DefaultWorkingDirectory)'